import os
import shutil
import uuid

from typing import Optional

from fastapi import APIRouter, UploadFile, File, HTTPException, Form
from fastapi.responses import JSONResponse, FileResponse

from server.config import UPLOAD_DIR
from server.services.uigen_auditor import run_uigen_pipeline
from server.services.gemini_image_service import generate_enhanced_ui

router = APIRouter(prefix="/uigen", tags=["uigen"])


@router.post("/generate", summary="Run the UIGen 6-phase audit pipeline")
async def uigen_generate(
    ui_image: UploadFile = File(...),
    audit_json: Optional[UploadFile] = File(None),
):
    """
    Accepts a UI screenshot and optional JSON audit data.
    Runs the full UIGen pipeline (phases 1–3, 5, 6) and returns
    annotated image URLs + design prompt.
    """
    try:
        # Save uploaded image
        img_id = uuid.uuid4().hex[:8]
        img_ext = os.path.splitext(ui_image.filename)[1] if ui_image.filename else ".png"
        img_path = os.path.join(str(UPLOAD_DIR), f"{img_id}_uigen{img_ext}")

        with open(img_path, "wb") as f:
            shutil.copyfileobj(ui_image.file, f)

        # Save uploaded JSON if provided
        json_path = ""
        if audit_json:
            json_path = os.path.join(str(UPLOAD_DIR), f"{img_id}_uigen_audit.json")
            with open(json_path, "wb") as f:
                shutil.copyfileobj(audit_json.file, f)

        # Execute pipeline
        result = run_uigen_pipeline(
            ui_image_path=img_path,
            audit_json_path=json_path,
        )

        if "error" in result:
            raise HTTPException(status_code=500, detail=result["error"])

        return result

    except HTTPException:
        raise
    except Exception as e:
        print(f"Error in uigen_generate: {e}")
        return JSONResponse(status_code=500, content={"error": str(e)})


@router.post("/gemini-image", summary="Generate enhanced UI using Gemini image generation")
async def uigen_gemini_image(
    ui_image: UploadFile = File(...),
    prompt: str = Form(...),
):
    """
    Accepts a UI screenshot and a design prompt.
    Calls Gemini image generation and returns the URL of the generated image.
    """
    try:
        img_id = uuid.uuid4().hex[:8]
        img_ext = os.path.splitext(ui_image.filename)[1] if ui_image.filename else ".png"
        img_path = os.path.join(str(UPLOAD_DIR), f"{img_id}_gemini_ref{img_ext}")

        with open(img_path, "wb") as f:
            shutil.copyfileobj(ui_image.file, f)

        result = generate_enhanced_ui(prompt=prompt, reference_image_path=img_path)

        if "error" in result:
            raise HTTPException(status_code=500, detail=result["error"])

        return result

    except HTTPException:
        raise
    except Exception as e:
        print(f"Error in uigen_gemini_image: {e}")
        return JSONResponse(status_code=500, content={"error": str(e)})


@router.get("/image/{filename}", summary="Serve a UIGen pipeline output image")
async def get_uigen_image(filename: str):
    """Serve images generated by the UIGen pipeline."""
    file_path = os.path.join(str(UPLOAD_DIR), filename)

    if os.path.exists(file_path):
        return FileResponse(file_path, media_type="image/png")

    return JSONResponse(status_code=404, content={"error": "Image not found"})
